### ISSUE TITLE
Error: No such file or directory, access `c:\Users\Mark\command-alias`

### ISSUE THREAD

**Issue by KyleMit** [ArturoDent/command-alias#5]
Love the idea, but seem to be getting an error when installing / running on my VS Code instance.  I get the following error in the VS Code Dev Tools:

> Error: ENOENT: no such file or directory, access 'c:\Users\Mark\command-alias'

[![image](https://user-images.githubusercontent.com/4307307/191114635-5b88c575-5d15-4aa0-8f1f-54fca3d74176.png)](https://user-images.githubusercontent.com/4307307/191114251-84bdee05-5412-4da3-8fcc-f43489809095.png)

Looks like that path is hardcoded as part of the `package.json`:

https://github.com/ArturoDent/command-alias/blob/21f737d0e773f9187cd5dccf91ed3ec4908fc116/package.json#L132-L138

**Comment by ArturoDent** [comment]
Thanks for finding this - it is a maddening "feature" of vscode that when debugging an extension like this it occasionally adds that info to the `package.json` - usually near the top but sometimes at the bottom.  There was a related GH issue that was being fixed wherein I asked if it would fix this behaviour too and I was told it would.  But it didn't.

Looks like I have to file an issue.

Anyhow, the issue is easy to fix.  Please try v0.5.6.

**Comment by KyleMit** [comment]
Ahh... thank you so much for the quick turn around - that fixed it!

Just as an FYI - interestingly, this error completely borked my local VS Code environment.  All extensions failed to load, including the `@builtins` like `git`, so VS Code almost completely falls over, and unfortunately, even tools like `Help: Start Extension Bisect` didn't seem to properly identify this package.  

But back to up and running in either case.  Thanks for the quick release!
